/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("InvoicesObjectPageObjectPage journey");

        opaTest("Navigate to InvoicesObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheInvoicesListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheInvoicesListGenerated.onTable().iCheckRows();
            When.onTheInvoicesListGenerated.onTable().iPressRow(0);

            Then.onTheInvoicesObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheInvoicesObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheInvoicesObjectPageGenerated.iPressSectionIconTabFilterButton("HeaderFacet");
            Then.onTheInvoicesObjectPageGenerated.iCheckSection({ section: "HeaderFacet" });
            Then.onTheInvoicesObjectPageGenerated.onForm({ section: "HeaderFacet" }).iCheckField({ property: "documentNumber" });
            Then.onTheInvoicesObjectPageGenerated.onForm({ section: "HeaderFacet" }).iCheckField({ property: "documentDate" });
            Then.onTheInvoicesObjectPageGenerated.onForm({ section: "HeaderFacet" }).iCheckField({ property: "totalAmount" });
            Then.onTheInvoicesObjectPageGenerated.onForm({ section: "HeaderFacet" }).iCheckField({ property: "currency" });
            Then.onTheInvoicesObjectPageGenerated.onForm({ section: "HeaderFacet" }).iCheckField({ property: "taxAmount" });
            Then.onTheInvoicesObjectPageGenerated.onForm({ section: "HeaderFacet" }).iCheckField({ property: "vendorCode" });
            Then.onTheInvoicesObjectPageGenerated.onForm({ section: "HeaderFacet" }).iCheckField({ property: "vendorName" });
            Then.onTheInvoicesObjectPageGenerated.onForm({ section: "HeaderFacet" }).iCheckField({ property: "vendorAccountNumber" });
            When.onTheInvoicesObjectPageGenerated.iPressSectionIconTabFilterButton("ItemsFacet");
            Then.onTheInvoicesObjectPageGenerated.iCheckSection({ section: "ItemsFacet" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});